// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NgGold.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NgGold.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231116090803_createBusiness")]
    partial class createBusiness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NgGold.Models.Business", b =>
                {
                    b.Property<string>("Cac_doc")
                        .HasColumnType("text")
                        .HasColumnName("cac_doc");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Created_by")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("Estimated_income")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_income");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("Is_verified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("Subscription")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription");

                    b.Property<long>("Subsidiary_of")
                        .HasColumnType("bigint")
                        .HasColumnName("subsidiary_of");

                    b.Property<DateTime>("Trial_ends")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends");

                    b.HasKey("Cac_doc");

                    b.ToTable("business");
                });

            modelBuilder.Entity("NgGold.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer")
                        .HasColumnName("account_status");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("reset_token");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("User_businessCac_doc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("User_businessCac_doc");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NgGold.Models.Users", b =>
                {
                    b.HasOne("NgGold.Models.Business", "User_business")
                        .WithMany()
                        .HasForeignKey("User_businessCac_doc");

                    b.Navigation("User_business");
                });
#pragma warning restore 612, 618
        }
    }
}
